// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var Component1$ReactHooksTemplate = require("./Component1.bs.js");
var Component2$ReactHooksTemplate = require("./Component2.bs.js");

var url = ReasonReactRouter.useUrl(undefined, /* () */0);

var match = url[/* path */0];

var nowShowing;

var exit = 0;

if (match) {
  switch (match[0]) {
    case "/" : 
    case "v1" : 
        if (match[1]) {
          nowShowing = "NotFound";
        } else {
          exit = 1;
        }
        break;
    case "v2" : 
        nowShowing = match[1] ? "NotFound" : React.createElement(Component2$ReactHooksTemplate.make, {
                greeting: "Hello!"
              });
        break;
    default:
      nowShowing = "NotFound";
  }
} else {
  exit = 1;
}

if (exit === 1) {
  ReasonReactRouter.replace("v1");
  nowShowing = React.createElement(Component1$ReactHooksTemplate.make, {
        message: "Hello! Click this text."
      });
}

function App(Props) {
  return React.createElement("div", undefined, nowShowing);
}

var make = App;

exports.url = url;
exports.nowShowing = nowShowing;
exports.make = make;
/* url Not a pure module */
